service: stfn-serverless
frameworkVersion: '2'

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
     Resource:
      - "arn:aws:dynamodb:us-east-1:348401656581:table/Employees"

functions:
  listAll:
    handler: ./dist/handler.listAll
    description: List all employees
    events:
      - http:
          path: /employees
          method: get
          cors: true
  findById:
    handler: ./dist/handler.findById
    description: Find employee by id
    events:
      - http:
          path: /employees/{employeeId}
          method: get
          cors: true
  create:
    handler: ./dist/handler.create
    description: Create employee
    events:
      - http:
          path: /employees
          method: post
          cors: true
  update:
    handler: ./dist/handler.update
    description: Update employee
    events:
      - http:
          path: /employees/{employeeId}
          method: put
          cors: true
  delete:
    handler: ./dist/handler.deleteFunction
    description: Delete employees
    events:
      - http:
          path: /employees/{employeeId}
          method: delete
          cors: true
